[gd_resource type="Theme" format=3]

[resource]
default_font_size = 14

[resource/label/colors/font_color]
type = "Color"
color = Color(1, 1, 1, 1)

[resource/button/colors/font_color]
type = "Color"
color = Color(1, 1, 1, 1)

[resource/button/colors/font_focus_color]
type = "Color"
color = Color(1, 1, 0.5, 1)

[resource/panelcontainer/styles/panel]
type = "StyleBoxFlat"
bg_color = Color(0.2, 0.2, 0.25, 1)
border_width_left = 1
border_width_top = 1
border_width_right = 1
border_width_bottom = 1
border_color = Color(0.5, 0.5, 0.55, 1)
